//zomato skko banayenge JS ke helpse
//dummy data of all restaurant hona chahiye
//1.restauarant image,restaurant name,rating,food type,price for two,location,distance ,offers,alchol serve,restaurant opening time ,restaurant closing time,
//all thsese informations needed to be stored in an object

// difffernt restaurant  ka data differnt objects ke me store hoga and all these objects needed to be stored in an array

    const restaurants = [
    {
        image: 'fifth',
        name: 'Barbeque Nation ',
        rating: '5.19',
        food_type: 'Middle Eastern',
        Price_For_Two: 1386,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '6.82',
        offers: 9,
        alchol: true,
        restaurant_opening_time: 10,
        restaurant_closing_time: 22
    },
    {
        image: 'eighth',
        name: 'Olive Garden ',
        rating: '1.40',
        food_type: 'Mexican',
        Price_For_Two: 1252,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '6.74',
        offers: 11,
        alchol: true,
        restaurant_opening_time: 6,
        restaurant_closing_time: 18
    },
    {
        image: 'eighth',
        name: 'Gaggan ',
        rating: '3.00',
        food_type: 'Italian',
        Price_For_Two: 767,
        locations: 'New York City, USA',
        distance_from_customers_house: '8.34',
        offers: 24,
        alchol: true,
        restaurant_opening_time: 5,
        restaurant_closing_time: 17
    },
    {
        image: 'third',
        name: 'The Fat Duck ',
        rating: '1.77',
        food_type: 'Mexican',
        Price_For_Two: 329,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '9.31',
        offers: 20,
        alchol: false,
        restaurant_opening_time: 3,
        restaurant_closing_time: 15
    },
    {
        image: 'fifth',
        name: 'Indian Accent ',
        rating: '5.95',
        food_type: 'French',
        Price_For_Two: 1755,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '7.26',
        offers: 10,
        alchol: false,
        restaurant_opening_time: 19,
        restaurant_closing_time: 7
    },
    {
        image: 'second',
        name: 'Indian Accent ',
        rating: '2.17',
        food_type: 'Middle Eastern',
        Price_For_Two: 1418,
        locations: 'Bray, United Kingdom',
        distance_from_customers_house: '7.98',
        offers: 1,
        alchol: true,
        restaurant_opening_time: 10,
        restaurant_closing_time: 22
    },
    {
        image: 'fourth',
        name: "Haldiram's ",
        rating: '2.13',
        food_type: 'Mexican',
        Price_For_Two: 1077,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '9.91',
        offers: 11,
        alchol: true,
        restaurant_opening_time: 6,
        restaurant_closing_time: 18
    },
    {
        image: 'tenth',
        name: 'Bukhara ',
        rating: '1.10',
        food_type: 'Thai',
        Price_For_Two: 364,
        locations: 'The Lodhi, New Delhi, India',
        distance_from_customers_house: '6.14',
        offers: 1,
        alchol: false,
        restaurant_opening_time: 11,
        restaurant_closing_time: 23
    },
    {
        image: 'seventh',
        name: 'Barbeque Nation ',
        rating: '3.94',
        food_type: 'Chinese',
        Price_For_Two: 1557,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '5.65',
        offers: 5,
        alchol: true,
        restaurant_opening_time: 13,
        restaurant_closing_time: 1
    },
    {
        image: 'seventh',
        name: 'Noma ',
        rating: '4.51',
        food_type: 'Chinese',
        Price_For_Two: 2025,
        locations: 'New York City, USA',
        distance_from_customers_house: '2.15',
        offers: 19,
        alchol: false,
        restaurant_opening_time: 5,
        restaurant_closing_time: 17
    },
    {
        image: 'third',
        name: 'Gaggan ',
        rating: '5.03',
        food_type: 'French',
        Price_For_Two: 2214,
        locations: 'Multiple Cities, USA',
        distance_from_customers_house: '9.19',
        offers: 8,
        alchol: false,
        restaurant_opening_time: 0,
        restaurant_closing_time: 12
    },
    {
        image: 'fourth',
        name: 'Indian Accent ',
        rating: '5.73',
        food_type: 'French',
        Price_For_Two: 1720,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '7.00',
        offers: 14,
        alchol: false,
        restaurant_opening_time: 12,
        restaurant_closing_time: 0
    },
    {
        image: 'second',
        name: 'Barbeque Nation ',
        rating: '5.02',
        food_type: 'Thai',
        Price_For_Two: 2207,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '3.71',
        offers: 14,
        alchol: false,
        restaurant_opening_time: 2,
        restaurant_closing_time: 14
    },
    {
        image: 'ninth',
        name: 'The Fat Duck ',
        rating: '3.23',
        food_type: 'French',
        Price_For_Two: 1733,
        locations: 'The Lodhi, New Delhi, India',
        distance_from_customers_house: '3.57',
        offers: 26,
        alchol: false,
        restaurant_opening_time: 11,
        restaurant_closing_time: 23
    },
    {
        image: 'tenth',
        name: 'The Fat Duck ',
        rating: '1.04',
        food_type: 'Chinese',
        Price_For_Two: 1977,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '2.03',
        offers: 25,
        alchol: true,
        restaurant_opening_time: 4,
        restaurant_closing_time: 16
    },
    {
        image: 'sixth',
        name: "Haldiram's ",
        rating: '2.87',
        food_type: 'Thai',
        Price_For_Two: 1980,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '5.56',
        offers: 22,
        alchol: false,
        restaurant_opening_time: 7,
        restaurant_closing_time: 19
    },
    {
        image: 'seventh',
        name: 'The Fat Duck ',
        rating: '1.04',
        food_type: 'Thai',
        Price_For_Two: 1881,
        locations: 'Multiple Cities, USA',
        distance_from_customers_house: '10.84',
        offers: 3,
        alchol: false,
        restaurant_opening_time: 2,
        restaurant_closing_time: 14
    },
    {
        image: 'fourth',
        name: 'Karavalli ',
        rating: '3.46',
        food_type: 'Middle Eastern',
        Price_For_Two: 2364,
        locations: 'The Lodhi, New Delhi, India',
        distance_from_customers_house: '3.29',
        offers: 29,
        alchol: true,
        restaurant_opening_time: 14,
        restaurant_closing_time: 2
    },
    {
        image: 'third',
        name: "Haldiram's ",
        rating: '3.70',
        food_type: 'Thai',
        Price_For_Two: 1452,
        locations: 'The Lodhi, New Delhi, India',
        distance_from_customers_house: '3.50',
        offers: 26,
        alchol: false,
        restaurant_opening_time: 15,
        restaurant_closing_time: 3
    },
    {
        image: 'third',
        name: 'Barbeque Nation ',
        rating: '1.86',
        food_type: 'Indian',
        Price_For_Two: 2281,
        locations: 'New York City, USA',
        distance_from_customers_house: '1.34',
        offers: 2,
        alchol: true,
        restaurant_opening_time: 21,
        restaurant_closing_time: 9
    },
    {
        image: 'first',
        name: "Haldiram's ",
        rating: '1.23',
        food_type: 'Thai',
        Price_For_Two: 1356,
        locations: 'The Lodhi, New Delhi, India',
        distance_from_customers_house: '10.93',
        offers: 3,
        alchol: false,
        restaurant_opening_time: 16,
        restaurant_closing_time: 4
    },
    {
        image: 'second',
        name: 'Bukhara ',
        rating: '3.22',
        food_type: 'Indian',
        Price_For_Two: 1536,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '7.18',
        offers: 22,
        alchol: false,
        restaurant_opening_time: 17,
        restaurant_closing_time: 5
    },
    {
        image: 'seventh',
        name: 'Le Bernardin ',
        rating: '3.94',
        food_type: 'Mexican',
        Price_For_Two: 1407,
        locations: 'Multiple Cities, USA',
        distance_from_customers_house: '9.17',
        offers: 24,
        alchol: true,
        restaurant_opening_time: 16,
        restaurant_closing_time: 4
    },
    {
        image: 'fourth',
        name: 'Bukhara ',
        rating: '2.75',
        food_type: 'American',
        Price_For_Two: 2361,
        locations: 'The Lodhi, New Delhi, India',
        distance_from_customers_house: '5.61',
        offers: 29,
        alchol: false,
        restaurant_opening_time: 4,
        restaurant_closing_time: 16
    },
    {
        image: 'fourth',
        name: "Haldiram's ",
        rating: '1.60',
        food_type: 'Mediterranean',
        Price_For_Two: 224,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '4.69',
        offers: 14,
        alchol: false,
        restaurant_opening_time: 20,
        restaurant_closing_time: 8
    },
    {
        image: 'ninth',
        name: 'Noma ',
        rating: '5.69',
        food_type: 'American',
        Price_For_Two: 215,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '9.44',
        offers: 24,
        alchol: true,
        restaurant_opening_time: 10,
        restaurant_closing_time: 22
    },
    {
        image: 'seventh',
        name: 'Barbeque Nation ',
        rating: '4.21',
        food_type: 'Thai',
        Price_For_Two: 753,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '5.43',
        offers: 7,
        alchol: false,
        restaurant_opening_time: 22,
        restaurant_closing_time: 10
    },
    {
        image: 'fifth',
        name: 'Le Bernardin ',
        rating: '5.83',
        food_type: 'Indian',
        Price_For_Two: 1495,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '6.89',
        offers: 12,
        alchol: false,
        restaurant_opening_time: 13,
        restaurant_closing_time: 1
    },
    {
        image: 'third',
        name: 'Le Bernardin ',
        rating: '3.56',
        food_type: 'Indian',
        Price_For_Two: 2366,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '4.89',
        offers: 21,
        alchol: true,
        restaurant_opening_time: 3,
        restaurant_closing_time: 15
    },
    {
        image: 'second',
        name: 'Karavalli ',
        rating: '3.98',
        food_type: 'Italian',
        Price_For_Two: 1982,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '2.87',
        offers: 5,
        alchol: false,
        restaurant_opening_time: 18,
        restaurant_closing_time: 6
    },
    {
        image: 'sixth',
        name: 'Le Bernardin ',
        rating: '2.94',
        food_type: 'French',
        Price_For_Two: 1438,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '9.12',
        offers: 7,
        alchol: false,
        restaurant_opening_time: 20,
        restaurant_closing_time: 8
    },
    {
        image: 'ninth',
        name: 'Indian Accent ',
        rating: '3.96',
        food_type: 'Thai',
        Price_For_Two: 1106,
        locations: 'New York City, USA',
        distance_from_customers_house: '7.75',
        offers: 9,
        alchol: false,
        restaurant_opening_time: 20,
        restaurant_closing_time: 8
    },
    {
        image: 'seventh',
        name: 'Noma ',
        rating: '1.41',
        food_type: 'Thai',
        Price_For_Two: 1554,
        locations: 'New York City, USA',
        distance_from_customers_house: '3.82',
        offers: 25,
        alchol: false,
        restaurant_opening_time: 2,
        restaurant_closing_time: 14
    },
    {
        image: 'seventh',
        name: "Haldiram's ",
        rating: '1.73',
        food_type: 'Thai',
        Price_For_Two: 269,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '7.54',
        offers: 29,
        alchol: false,
        restaurant_opening_time: 5,
        restaurant_closing_time: 17
    },
    {
        image: 'third',
        name: 'The Fat Duck ',
        rating: '2.59',
        food_type: 'Chinese',
        Price_For_Two: 707,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '2.64',
        offers: 5,
        alchol: false,
        restaurant_opening_time: 21,
        restaurant_closing_time: 9
    },
    {
        image: 'first',
        name: 'The Fat Duck ',
        rating: '1.86',
        food_type: 'Mexican',
        Price_For_Two: 1137,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '4.28',
        offers: 16,
        alchol: true,
        restaurant_opening_time: 12,
        restaurant_closing_time: 0
    },
    {
        image: 'third',
        name: 'Karavalli ',
        rating: '5.99',
        food_type: 'Japanese',
        Price_For_Two: 1480,
        locations: 'Bray, United Kingdom',
        distance_from_customers_house: '5.19',
        offers: 9,
        alchol: false,
        restaurant_opening_time: 18,
        restaurant_closing_time: 6
    },
    {
        image: 'fifth',
        name: 'Barbeque Nation ',
        rating: '1.57',
        food_type: 'Mediterranean',
        Price_For_Two: 216,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '7.24',
        offers: 21,
        alchol: true,
        restaurant_opening_time: 20,
        restaurant_closing_time: 8
    },
    {
        image: 'fourth',
        name: 'The Fat Duck ',
        rating: '2.57',
        food_type: 'Middle Eastern',
        Price_For_Two: 302,
        locations: 'Multiple Cities, USA',
        distance_from_customers_house: '1.27',
        offers: 2,
        alchol: true,
        restaurant_opening_time: 8,
        restaurant_closing_time: 20
    },
    {
        image: 'first',
        name: 'Olive Garden ',
        rating: '5.97',
        food_type: 'Italian',
        Price_For_Two: 351,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '5.77',
        offers: 13,
        alchol: false,
        restaurant_opening_time: 8,
        restaurant_closing_time: 20
    },
    {
        image: 'eighth',
        name: 'Noma ',
        rating: '2.01',
        food_type: 'Mediterranean',
        Price_For_Two: 2290,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '9.65',
        offers: 12,
        alchol: false,
        restaurant_opening_time: 7,
        restaurant_closing_time: 19
    },
    {
        image: 'sixth',
        name: 'Olive Garden ',
        rating: '5.22',
        food_type: 'American',
        Price_For_Two: 2412,
        locations: 'Bray, United Kingdom',
        distance_from_customers_house: '5.51',
        offers: 18,
        alchol: false,
        restaurant_opening_time: 17,
        restaurant_closing_time: 5
    },
    {
        image: 'fifth',
        name: 'Indian Accent ',
        rating: '2.75',
        food_type: 'Mediterranean',
        Price_For_Two: 756,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '7.22',
        offers: 21,
        alchol: true,
        restaurant_opening_time: 14,
        restaurant_closing_time: 2
    },
    {
        image: 'eighth',
        name: "Haldiram's ",
        rating: '1.53',
        food_type: 'Japanese',
        Price_For_Two: 737,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '1.70',
        offers: 17,
        alchol: true,
        restaurant_opening_time: 11,
        restaurant_closing_time: 23
    },
    {
        image: 'sixth',
        name: 'Karavalli ',
        rating: '4.90',
        food_type: 'Japanese',
        Price_For_Two: 431,
        locations: 'Bray, United Kingdom',
        distance_from_customers_house: '6.36',
        offers: 6,
        alchol: true,
        restaurant_opening_time: 6,
        restaurant_closing_time: 18
    },
    {
        image: 'second',
        name: 'Karavalli ',
        rating: '2.53',
        food_type: 'Indian',
        Price_For_Two: 1141,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '10.92',
        offers: 20,
        alchol: false,
        restaurant_opening_time: 23,
        restaurant_closing_time: 11
    },
    {
        image: 'ninth',
        name: 'Bukhara ',
        rating: '3.34',
        food_type: 'Middle Eastern',
        Price_For_Two: 1235,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '5.15',
        offers: 2,
        alchol: false,
        restaurant_opening_time: 22,
        restaurant_closing_time: 10
    },
    {
        image: 'fourth',
        name: 'Bukhara ',
        rating: '1.63',
        food_type: 'French',
        Price_For_Two: 718,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '3.30',
        offers: 6,
        alchol: false,
        restaurant_opening_time: 11,
        restaurant_closing_time: 23
    },
    {
        image: 'sixth',
        name: 'Indian Accent ',
        rating: '3.74',
        food_type: 'Italian',
        Price_For_Two: 1695,
        locations: 'The Lodhi, New Delhi, India',
        distance_from_customers_house: '6.29',
        offers: 26,
        alchol: false,
        restaurant_opening_time: 3,
        restaurant_closing_time: 15
    },
    {
        image: 'fifth',
        name: "Haldiram's ",
        rating: '2.06',
        food_type: 'Middle Eastern',
        Price_For_Two: 2068,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '10.38',
        offers: 3,
        alchol: false,
        restaurant_opening_time: 18,
        restaurant_closing_time: 6
    },
    {
        image: 'fifth',
        name: 'Gaggan ',
        rating: '2.84',
        food_type: 'Japanese',
        Price_For_Two: 1549,
        locations: 'Bangkok, Thailand',
        distance_from_customers_house: '9.47',
        offers: 4,
        alchol: true,
        restaurant_opening_time: 14,
        restaurant_closing_time: 2
    },
    {
        image: 'seventh',
        name: 'Gaggan ',
        rating: '2.02',
        food_type: 'Middle Eastern',
        Price_For_Two: 2326,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '4.25',
        offers: 15,
        alchol: false,
        restaurant_opening_time: 16,
        restaurant_closing_time: 4
    },
    {
        image: 'tenth',
        name: 'Olive Garden ',
        rating: '1.15',
        food_type: 'French',
        Price_For_Two: 1296,
        locations: 'Multiple Cities, USA',
        distance_from_customers_house: '8.13',
        offers: 2,
        alchol: true,
        restaurant_opening_time: 10,
        restaurant_closing_time: 22
    },
    {
        image: 'eighth',
        name: 'Noma ',
        rating: '1.59',
        food_type: 'Mediterranean',
        Price_For_Two: 2093,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '7.10',
        offers: 7,
        alchol: false,
        restaurant_opening_time: 17,
        restaurant_closing_time: 5
    },
    {
        image: 'third',
        name: 'Bukhara ',
        rating: '1.73',
        food_type: 'French',
        Price_For_Two: 1816,
        locations: 'Bray, United Kingdom',
        distance_from_customers_house: '5.84',
        offers: 17,
        alchol: false,
        restaurant_opening_time: 14,
        restaurant_closing_time: 2
    },
    {
        image: 'fifth',
        name: 'Gaggan ',
        rating: '4.31',
        food_type: 'French',
        Price_For_Two: 807,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '4.16',
        offers: 13,
        alchol: false,
        restaurant_opening_time: 11,
        restaurant_closing_time: 23
    },
    {
        image: 'second',
        name: "Haldiram's ",
        rating: '2.88',
        food_type: 'Italian',
        Price_For_Two: 990,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '10.06',
        offers: 22,
        alchol: true,
        restaurant_opening_time: 5,
        restaurant_closing_time: 17
    },
    {
        image: 'sixth',
        name: 'Karavalli ',
        rating: '3.32',
        food_type: 'Chinese',
        Price_For_Two: 2283,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '4.64',
        offers: 26,
        alchol: false,
        restaurant_opening_time: 18,
        restaurant_closing_time: 6
    },
    {
        image: 'tenth',
        name: 'The Fat Duck ',
        rating: '4.10',
        food_type: 'Italian',
        Price_For_Two: 108,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '7.65',
        offers: 10,
        alchol: false,
        restaurant_opening_time: 13,
        restaurant_closing_time: 1
    },
    {
        image: 'eighth',
        name: 'Indian Accent ',
        rating: '2.92',
        food_type: 'Chinese',
        Price_For_Two: 1703,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '5.48',
        offers: 29,
        alchol: false,
        restaurant_opening_time: 18,
        restaurant_closing_time: 6
    },
    {
        image: 'third',
        name: 'Noma ',
        rating: '4.56',
        food_type: 'Mexican',
        Price_For_Two: 1973,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '8.93',
        offers: 26,
        alchol: true,
        restaurant_opening_time: 6,
        restaurant_closing_time: 18
    },
    {
        image: 'third',
        name: 'Le Bernardin ',
        rating: '5.12',
        food_type: 'Indian',
        Price_For_Two: 740,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '6.69',
        offers: 6,
        alchol: false,
        restaurant_opening_time: 12,
        restaurant_closing_time: 0
    },
    {
        image: 'seventh',
        name: 'Noma ',
        rating: '1.28',
        food_type: 'American',
        Price_For_Two: 184,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '10.97',
        offers: 4,
        alchol: false,
        restaurant_opening_time: 7,
        restaurant_closing_time: 19
    },
    {
        image: 'fourth',
        name: "Haldiram's ",
        rating: '3.73',
        food_type: 'Indian',
        Price_For_Two: 317,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '6.61',
        offers: 20,
        alchol: false,
        restaurant_opening_time: 7,
        restaurant_closing_time: 19
    },
    {
        image: 'eighth',
        name: 'Noma ',
        rating: '1.64',
        food_type: 'Mediterranean',
        Price_For_Two: 487,
        locations: 'The Lodhi, New Delhi, India',
        distance_from_customers_house: '1.84',
        offers: 10,
        alchol: false,
        restaurant_opening_time: 12,
        restaurant_closing_time: 0
    },
    {
        image: 'ninth',
        name: 'Le Bernardin ',
        rating: '2.00',
        food_type: 'Thai',
        Price_For_Two: 1508,
        locations: 'The Gateway Hotel, Bengaluru, India',
        distance_from_customers_house: '9.76',
        offers: 14,
        alchol: true,
        restaurant_opening_time: 1,
        restaurant_closing_time: 13
    },
    {
        image: 'fifth',
        name: 'Bukhara ',
        rating: '3.26',
        food_type: 'Japanese',
        Price_For_Two: 359,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '7.76',
        offers: 14,
        alchol: true,
        restaurant_opening_time: 18,
        restaurant_closing_time: 6
    },
    {
        image: 'sixth',
        name: 'Karavalli ',
        rating: '4.30',
        food_type: 'French',
        Price_For_Two: 2170,
        locations: 'New York City, USA',
        distance_from_customers_house: '3.04',
        offers: 1,
        alchol: false,
        restaurant_opening_time: 11,
        restaurant_closing_time: 23
    },
    {
        image: 'eighth',
        name: 'Barbeque Nation ',
        rating: '5.72',
        food_type: 'Italian',
        Price_For_Two: 1333,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '8.86',
        offers: 20,
        alchol: false,
        restaurant_opening_time: 2,
        restaurant_closing_time: 14
    },
    {
        image: 'sixth',
        name: 'Olive Garden ',
        rating: '1.58',
        food_type: 'Middle Eastern',
        Price_For_Two: 684,
        locations: 'Bray, United Kingdom',
        distance_from_customers_house: '5.35',
        offers: 14,
        alchol: true,
        restaurant_opening_time: 4,
        restaurant_closing_time: 16
    },
    {
        image: 'fifth',
        name: "Haldiram's ",
        rating: '2.32',
        food_type: 'American',
        Price_For_Two: 818,
        locations: 'Bray, United Kingdom',
        distance_from_customers_house: '4.94',
        offers: 16,
        alchol: true,
        restaurant_opening_time: 3,
        restaurant_closing_time: 15
    },
    {
        image: 'first',
        name: 'Olive Garden ',
        rating: '3.15',
        food_type: 'French',
        Price_For_Two: 1011,
        locations: 'Copenhagen, Denmark',
        distance_from_customers_house: '3.22',
        offers: 3,
        alchol: true,
        restaurant_opening_time: 20,
        restaurant_closing_time: 8
    },
    {
        image: 'first',
        name: 'Gaggan ',
        rating: '1.22',
        food_type: 'Indian',
        Price_For_Two: 136,
        locations: 'New York City, USA',
        distance_from_customers_house: '5.33',
        offers: 17,
        alchol: false,
        restaurant_opening_time: 3,
        restaurant_closing_time: 15
    },
    {
        image: 'seventh',
        name: 'Le Bernardin ',
        rating: '1.04',
        food_type: 'Japanese',
        Price_For_Two: 372,
        locations: 'New York City, USA',
        distance_from_customers_house: '9.24',
        offers: 24,
        alchol: false,
        restaurant_opening_time: 1,
        restaurant_closing_time: 13
    },
    {
        image: 'eighth',
        name: 'Indian Accent ',
        rating: '2.47',
        food_type: 'French',
        Price_For_Two: 1496,
        locations: 'Multiple Cities, India',
        distance_from_customers_house: '4.16',
        offers: 16,
        alchol: false,
        restaurant_opening_time: 19,
        restaurant_closing_time: 7
    },
    {
        image: 'first',
        name: 'Le Bernardin ',
        rating: '1.70',
        food_type: 'Mediterranean',
        Price_For_Two: 1828,
        locations: 'The Lodhi, New Delhi, India',
        distance_from_customers_house: '10.67',
        offers: 21,
        alchol: false,
        restaurant_opening_time: 4,
        restaurant_closing_time: 16
    },
    {
        image: 'tenth',
        name: 'Barbeque Nation ',
        rating: '4.79',
        food_type: 'Thai',
        Price_For_Two: 2434,
        locations: 'Multiple Cities, USA',
        distance_from_customers_house: '5.38',
        offers: 7,
        alchol: false,
        restaurant_opening_time: 2,
        restaurant_closing_time: 14
    },
    {
        image: 'eighth',
        name: "Haldiram's ",
        rating: '2.89',
        food_type: 'Chinese',
        Price_For_Two: 1812,
        locations: 'ITC Maurya, New Delhi, India',
        distance_from_customers_house: '4.28',
        offers: 13,
        alchol: true,
        restaurant_opening_time: 7,
        restaurant_closing_time: 19
    }
    ]

    const container = document.getElementById("restaurant-list");

function renderRestaurants(data) {
  container.innerHTML = ""; // clear previous cards

  data.forEach(rest => {
    // create card
    const card = document.createElement("div");
    card.classList.add("card");

    // card HTML
    card.innerHTML = `
      <img src="images/${restaurants.image}.jpg" alt="${rest.name}">
      <div class="info">
        <h3>${rest.name}</h3>
        <p>⭐ ${rest.rating} | ${rest.food_type}</p>
        <p>📍 ${rest.locations}</p>
        <p>💰 ₹${rest.Price_For_Two} for two</p>
        <p class="offers">${rest.offers} Offers Available</p>
        ${rest.alchol ? `<span class="tag">Alcohol</span>` : `<span class="tag">No Alcohol</span>`}
      </div>
    `;

    container.appendChild(card);
  });
}

// Initial render
renderRestaurants(restaurants);
